In [1]:
import pandas as pd
import numpy as np
import sys
import IPython
from IPython.display import display
from IPython.display import HTML, Javascript

In [2]:
HTML('''
<script>
  code_show=true; 
  function code_toggle() {
   if (code_show){
     $('div.input').hide();
   } else {
     $('div.input').show();
   }
   code_show = !code_show;
  } 
  $(document).ready(code_toggle);
</script>
<form action="javascript:code_toggle()">
  <input type="submit" value="Click here to toggle on/off the raw code.">
</form>''')

In [3]:
df = pd.read_csv('D:\data\salary\monthly_salary_brazil.csv', error_bad_lines=False, warn_bad_lines=False)
def get_stats(group):
    return {'min_salary': group.min(), 'max_salary': group.max(),
            'count': group.count(), 'mean_salary': group.mean()}

job_stats = df['total_salary'].groupby(df['job']).apply(get_stats).unstack()
job_stats = job_stats.sort_values('count',ascending=False)
job_stats = job_stats[job_stats['count']>1000]
job_stats.head()

,count,max_salary,mean_salary,min_salary
job,,,,
PROFESSOR EDUCACAO BASICA II,221178.0,80770.28,2546.708971,-16634.41
PROFESSOR EDUCACAO BASICA I,128705.0,95517.02,2521.459709,-13668.96
BENEFICIARIO DE SERVIDOR ESTADUAL-IPESP,91458.0,150218.40,3400.546510,0.00
AGENTE DE ORGANIZACAO ESCOLAR,43123.0,23735.10,1330.142941,-7606.74
BENEFICIARIO DA POLICIA MILITAR - CBPM,37725.0,50362.49,3720.696505,54.14

In [4]:
sector_stats = df['total_salary'].groupby(df['sector']).apply(get_stats).unstack()
sector_stats = sector_stats.sort_values('count',ascending=False)
sector_stats = sector_stats.iloc[:60]
sector_stats.head()

             count  max_salary  mean_salary  min_salary
sector
SPPREV    447539.0   342151.20  3666.302828    -3301.39
EDUCACAO  259238.0    63363.56  2231.600333   -25405.70
PM         83865.0   165161.58  3933.852857        0.00
SAUDE      49042.0    67978.00  3318.352076    -2743.81
SAP        44270.0    55241.36  2685.565100   -14581.84

In [5]:
def df2c3(df):
    data = {}
    categories = list(df.index.values)
    columns = []
    for col in df.columns:
        this_col = [col]
        this_col.extend(list(df[col].values))
        columns.append(this_col)
    data["columns"] = columns
    data["categories"] = categories
    return data

def df2c3_2(df):
    data = {}
    data["categories"] = list(sector_stats.index.values)
    columns = []
    for col in df.columns:
        this_col = [col]
        this_col.extend(list(sector_stats[col]))
        columns.append(this_col)
    data["columns"] = columns
    return data
sector_count=df2c3_2(sector_stats[['count', 'mean_salary']])

In [6]:
for i in range(10):
    locals()["job_count_{}_{}".format(i*10, (i+1)*10)] = df2c3(job_stats[['count']].iloc[i*10:(i+1)*10].sort_values("count", ascending=False).T)
for i in range(10):
    locals()["name_list_{}_{}".format(i*10, (i+1)*10)] = [col[0] for col in locals()["job_count_{}_{}".format(i*10, (i+1)*10)]['columns']]

In [7]:
for i in range(1, 4):
    locals()["count_{}".format(i)] = []
    locals()["count_{}".format(i)].append("count")
    locals()["salary_{}".format(i)] = []
    locals()["salary_{}".format(i)].append("mean_salary")
    locals()["index_{}".format(i)] = []
    for j in range( (i-1)*20+1 , i*20 +1): 
        locals()["count_{}".format(i)].append(sector_count["columns"][0][j])
        locals()["salary_{}".format(i)].append(sector_count["columns"][1][j])
        locals()["index_{}".format(i)].append(sector_count["categories"][j-1])

In [8]:
Javascript("""
           window.job_count_0_10={};
           window.job_count_10_20={};
           window.job_count_20_30={};
           window.job_count_30_40={};
           window.job_count_40_50={};
           window.job_count_50_60={};
           window.job_count_60_70={};
           window.job_count_70_80={};
           window.job_count_80_90={};
           window.job_count_90_100={};
           window.name_list_0_10={};
           window.name_list_10_20={};
           window.name_list_20_30={};
           window.name_list_30_40={};
           window.name_list_40_50={};
           window.name_list_50_60={};
           window.name_list_60_70={};
           window.name_list_70_80={};
           window.name_list_80_90={};
           window.name_list_90_100={};
           window.count_1={};
           window.count_2={};
           window.count_3={};
           window.salary_1={};
           window.salary_2={};
           window.salary_3={};
           window.index_1={};
           window.index_2={};
           window.index_3={};
           """.format(job_count_0_10,job_count_10_20, job_count_20_30,
                      job_count_30_40, job_count_40_50, job_count_50_60,
                      job_count_60_70, job_count_70_80, job_count_80_90,job_count_90_100,
                      name_list_0_10,name_list_10_20, name_list_20_30,
                      name_list_30_40, name_list_40_50, name_list_50_60,
                      name_list_60_70, name_list_70_80, name_list_80_90,name_list_90_100,
                     count_1, count_2, count_3, salary_1,salary_2,salary_3, index_1, index_2, index_3))

In [9]:
%%javascript
require.config({
   baseUrl: "",
   paths: { 
            d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min',
            c3: "//cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min"
          }
});

In [10]:
%%javascript
require(["d3", "c3"], function(d3, c3) {
window.d3 = d3;
window.c3 = c3;
});

In [11]:
%%javascript
$("head").append('<link href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.css" rel="stylesheet" />');
$("head").append('<style>.c3-line { stroke-width: 3px; }</style>');
$("head").append('<style>.explore_distribution {margin: 0px auto;background-color:#44c767;-moz-border-radius:14px;-webkit-border-radius:18px;border-radius:28px;border:1px solid #18ab29;display:inline-block;cursor:pointer;color:#ffffff;font-family:Arial;font-size:12px;padding:8px 31px;text-decoration:none;text-shadow:0px 1px 0px #2f6627;}</style>');
$("head").append('<style>.explore_distribution:hover {background-color:#5cbf2a;}</style>');
$("head").append('<style>.explore_distribution:active {position:relative;top:1px;}</style>');
$("head").append('<style>.explore_bar {margin: 0px auto;background-color:#44c767;-moz-border-radius:14px;-webkit-border-radius:28px;border-radius:28px;border:1px solid #18ab29;display:inline-block;cursor:pointer;color:#ffffff;font-family:Arial;font-size:12px;padding:16px 31px;text-decoration:none;text-shadow:0px 1px 0px #2f6627;}</style>');
$("head").append('<style>.explore_bar:hover {background-color:#5cbf2a;}</style>');
$("head").append('<style>.explore_bar:active {position:relative;top:1px;}</style>');
$("head").append('<style>#chart1{width: 800px;height: 400px;}</style>');

In [12]:
%%javascript
$("#chart1").remove();
element.append("<h2>Distributions of Public Jobs in Brazil by Count</h2><div id='chart1'></div><button type='button' class='explore_distribution'>Explore Whole Distribution Again</button>");

In [13]:
%%javascript
function draw_all(){
var chart = c3.generate({
    bindto: '#chart1',
    data: {
        columns: job_count_0_10["columns"],
        type : 'donut',
        onmouseover: function (d, i) { return d; },
    },
    donut: {
        title: "Jobs distribution",
        label: {
      format: function(value, ratio, id) {
        return value;
      }
    }

    }
});

setTimeout(function () {
    chart.load({
        columns: job_count_10_20["columns"],
    });
}, 6000);

setTimeout(function () {
    chart.unload({
        ids: name_list_0_10
    });
}, 7500);

setTimeout(function () {
    chart.load({
        columns: job_count_20_30["columns"]
    });
}, 13500);

setTimeout(function () {
    chart.unload({
        ids: name_list_10_20
    });
}, 15000);

setTimeout(function () {
    chart.load({
        columns: job_count_30_40["columns"]
    });
}, 21000);

setTimeout(function () {
    chart.unload({
        ids: name_list_20_30
    });
}, 22500);

setTimeout(function () {
    chart.load({
        columns: job_count_40_50["columns"]
    });
}, 28500);

setTimeout(function () {
    chart.unload({
        ids: name_list_30_40
    });
}, 30000);

setTimeout(function () {
    chart.load({
        columns: job_count_50_60["columns"]
    });
}, 36000);

setTimeout(function () {
    chart.unload({
        ids: name_list_40_50
    });
}, 37500);

setTimeout(function () {
    chart.load({
        columns: job_count_60_70["columns"]
    });
}, 43500);

setTimeout(function () {
    chart.unload({
        ids: name_list_50_60
    });
}, 45000);

setTimeout(function () {
    chart.load({
        columns: job_count_70_80["columns"]
    });
}, 51000);

setTimeout(function () {
    chart.unload({
        ids: name_list_60_70
    });
}, 52500);

setTimeout(function () {
    chart.load({
        columns: job_count_80_90["columns"]
    });
}, 58500);

setTimeout(function () {
    chart.unload({
        ids: name_list_70_80
    });
}, 60000);

setTimeout(function () {
    chart.load({
        columns: job_count_90_100["columns"]
    });
}, 66000);

setTimeout(function () {
    chart.unload({
        ids: name_list_80_90
    });
}, 67500);
}

draw_all();

d3.select('.explore_distribution').on('click', function(){
draw_all();
})

In [14]:
%%javascript
$("#chart2").remove();
element.append("<h2>Salary and Count for Public Jobs in Brazil</h2><div id='chart2'></div><button type='button' class='explore_bar'>Explore Again</button>");

In [15]:
%%javascript
function draw_bar(){
var chart = c3.generate({
    bindto: "#chart2",
    size: {height: 640 },
    data: {
        columns: [count_1, salary_1],
        type:"bar",
        types:{mean_salary: 'spline'},
        axes: {
        mean_salary: 'y2'
      }
    },
    axis: {
            x: {
                type:"category",
                categories: index_1
              },
            y2: {
        show: true 
      },
        y: {
        label: { 
          text: 'Count ',
          position: 'outer-middle'
        }
      },
      y2: {
        show: true,
        label: { 
          text: 'Mean Salary',
          position: 'outer-middle'
        }
      }
          },
    grid: {
            x: {show: true},
            y: { show: true}
        }       
});

setTimeout(function () {
    chart.load({
        columns: [count_2, salary_2],
        categories: index_2              
    });
}, 10000);

setTimeout(function () {
    chart.load({
        columns: [count_3, salary_3],
        categories: index_3              
    });
}, 20000);
}

draw_bar()

d3.select('.explore_bar').on('click', function(){
draw_bar();
})